---
- name: apt-get update; apt-get dist-upgrade
  apt: update_cache=yes upgrade=dist
  when: ansible_os_family == "Debian"

- name: yum update
  yum: name=* state=latest
  when: ansible_os_family == "RedHat"
