---
- name: create an Amazon EC2 instance
  hosts: localhost
  gather_facts: False
  vars_files:
    - vars/ec2_proftpd
  roles:
    - ec2_security_group_ftpd
    - ec2_create

- name: install ProFTPd on the newly created host
  hosts: ec2hosts
  sudo: yes
  user: '{{ ssh_user }}'
  vars_files:
    - vars/ec2_proftpd
  roles:
    - update_system
    - proftpd
    - { role: fail2ban, ssh: true, proftpd: true }
