---
- import_tasks: 1000-system.yml

- name: check if easyrsa directory exists
  stat:
    path: "{{ openvpn_server_easyrsa_dir }}"
  register: _easyrsa_dir
  tags:
    - openvpn
    - easyrsa

- import_tasks: 2000-install_easyrsa.yml
  when: not _easyrsa_dir.stat.exists

- import_tasks: 3000-configure_easyrsa.yml
- import_tasks: 4000-configure_openvpn.yml
- import_tasks: 5000-nftables.yml

- name: download openvpn config file
  fetch:
    src: "{{ openvpn_server_client_conf }}"
    dest: "{{ openvpn_server_config_download_path }}"
    flat: yes
