---
- name: apt-get install fail2ban
  apt: name=fail2ban
  when: ansible_os_family == "Debian"

- name: yum install fail2ban
  yum: name=fail2ban
  when: ansible_os_family == "RedHat"

- name: upload jail.conf
  template: src=jail.conf.j2 dest=/etc/fail2ban/jail.conf owner=root mode=0400
  notify: restart fail2ban
