---
- name: create an EC2 instance
  ec2: keypair={{ keypair }} instance_type={{ instance_type }} region={{ region }}
       zone={{ zone }} image={{ image }} group={{ security_group }} wait=yes
  register: ec2_info

- name: create a dynamic host environment
  add_host: hostname={{ item.public_ip }} groupname=ec2hosts
  with_items: ec2_info.instances

- name: wait for instances to listen on port {{ ssh_port }}
  wait_for: state=started host={{ item.public_ip }} port={{ ssh_port }}
  with_items: ec2_info.instances
